# This rule is not used by the project autorestartpod itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over stable.crazyfrank.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: autorestartpod
    app.kubernetes.io/managed-by: kustomize
  name: autorestartpod-admin-role
rules:
- apiGroups:
  - stable.crazyfrank.com
  resources:
  - autorestartpods
  verbs:
  - '*'
- apiGroups:
  - stable.crazyfrank.com
  resources:
  - autorestartpods/status
  verbs:
  - get
