---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - stable.crazyfrank.com
  resources:
  - autorestartpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.crazyfrank.com
  resources:
  - autorestartpods/finalizers
  verbs:
  - update
- apiGroups:
  - stable.crazyfrank.com
  resources:
  - autorestartpods/status
  verbs:
  - get
  - patch
  - update
